services:
  - type: web
    name: rtoc-wiki-api
    runtime: python
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: GITHUB_TOKEN
        sync: false
