tunnel: cf1df3b3-cb3b-48c1-a660-c159a92a67ea
credentials-file: C:\Users\user\.cloudflared\cf1df3b3-cb3b-48c1-a660-c159a92a67ea.json

ingress:
  - hostname: regressorstaleofcultivation.space
    service: http://127.0.0.1:8081
  - service: http_status:404
